import type { Metadata } from "next";
import "./globals.css";
import { EnvexProvider } from "@daniel-rose/envex";
import { EnvScript } from "@daniel-rose/envex/script";
import { getPublicEnv } from "@daniel-rose/envex/server";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialEnv = await getPublicEnv();

  return (
    <html lang="en">
      <body>
        <EnvScript />
        <EnvexProvider initialEnv={initialEnv}>{children}</EnvexProvider>
      </body>
    </html>
  );
}
