import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AutoBay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="/icon?<generated>" rel="icon" sizes="<generated>" type="image/<generated>" />
        <link href="/favicon.ico" rel="icon" sizes="any" />
        <link href="/apple-icon?<generated>" rel="apple-touch-icon" sizes="<generated>" type="image/<generated>" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${"dark"} `}>
        {/* <Navbar /> */}
        <main className="flex min-h-screen w-full flex-col items-center justify-center">{children}</main>
      </body>
    </html>
  );
}
